version: "3.7"
services:
  lorawan_coordinator:
    build: .
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql:3306
      - DB_USER=vmlacic
      - DB_PASSWORD=password
      - DB_DATABASE=lorawan_coordinator_dev
    command: [
      "./scripts/wait-for-it.sh", 
      "0.0.0.0:3306", 
      "lorawan_coordinator_dev",
      "vmlacic",
      "password",
      "npm", 
      "start"
    ]
  mysql:
    build: 
      context: ./mysql-service
      args:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=lorawan_coordinator_dev
        - MYSQL_USER=vmlacic
        - MYSQL_PASSWORD=password
    expose:
      - "3306"
